import { TenantConfig } from "./types";

export const biteConfig: TenantConfig = {
  id: "bite",
  name: "Bite",
  logo: "/brands/icons/bite.svg",
  enableBidirectional: true,
  datasets: [
    // Tier 1: Core Transactional Data
    {
      id: "kiosk-orders",
      name: "Kiosk Orders & Transactions",
      description:
        "Complete order history from all kiosks including items, customizations, payment methods, and check sizes",
      tagline: "Full transaction history across all kiosk locations",
      tables: [
        "Orders",
        "Order Items",
        "Customizations",
        "Payments",
        "Receipts",
        "Refunds",
      ],
      size: "89.4 GB",
      rows: "342M",
      tier: 1,
      locked: false,
      pricing: "$4 / location / month",
      refreshRate: "Real-time",
    },
    {
      id: "menu-performance",
      name: "Menu Performance",
      description:
        "Menu item analytics including popularity, prep times, upsell success rates, and BiteLift AI recommendation performance",
      tagline: "Menu optimization with AI recommendation insights",
      tables: [
        "Menu Items",
        "Item Performance",
        "Upsell Analytics",
        "BiteLift Recommendations",
        "Prep Time Metrics",
      ],
      size: "24.6 GB",
      rows: "86.3M",
      tier: 1,
      locked: false,
      pricing: "$3 / location / month",
      refreshRate: "Hourly",
    },
    // Tier 2: Operations & Analytics
    {
      id: "kiosk-performance",
      name: "Kiosk Operations",
      description:
        "Kiosk uptime, transaction speeds, error rates, session analytics, and peak time throughput metrics",
      tagline: "Comprehensive kiosk performance monitoring",
      tables: [
        "Kiosk Status",
        "Uptime Metrics",
        "Transaction Times",
        "Error Logs",
        "Session Analytics",
        "Peak Time Performance",
      ],
      size: "38.7 GB",
      rows: "156M",
      tier: 2,
      locked: true,
      pricing: "+$5 / location / month",
      refreshRate: "Real-time",
    },
    {
      id: "customer-behavior",
      name: "Customer Behavior Analytics",
      description:
        "Customer journey analysis, check size trends, order customization patterns, and loyalty insights",
      tagline: "Deep customer ordering behavior insights",
      tables: [
        "Customer Sessions",
        "Journey Analytics",
        "Check Size Trends",
        "Customization Patterns",
        "Repeat Customer Metrics",
      ],
      size: "52.3 GB",
      rows: "198M",
      tier: 2,
      locked: true,
      pricing: "+$6 / location / month",
      refreshRate: "Daily",
    },
    {
      id: "competitor-benchmarking",
      name: "Competitor Benchmarking",
      description:
        "Market intelligence including competitor menu pricing, item comparisons, market trends, and competitive positioning data",
      tagline: "Stay ahead with competitive market insights",
      tables: [
        "Competitor Pricing",
        "Menu Comparisons",
        "Market Trends",
        "Performance Benchmarks",
        "Market Share Analytics",
      ],
      size: "14.2 GB",
      rows: "98M",
      tier: 2,
      locked: true,
      pricing: "+$4 / location / month",
      refreshRate: "Daily",
    },
  ],
  customerDatasets: [
    {
      id: "store-information",
      name: "Store & Location Information",
      description:
        "Restaurant location details including address, operating hours, seating capacity, and store attributes",
      tagline: "Complete store profile and operational data",
      tables: [
        "Stores",
        "Operating Hours",
        "Store Attributes",
        "Location Details",
      ],
      size: "125 MB",
      rows: "2.4K",
      locked: false,
    },
    {
      id: "menu-information",
      name: "Menu Information",
      description:
        "Menu items, categories, pricing, ingredients, allergens, and nutritional information",
      tagline: "Complete menu catalog with all item details",
      tables: [
        "Menu Items",
        "Categories",
        "Pricing",
        "Ingredients",
        "Allergens",
        "Nutritional Info",
      ],
      size: "450 MB",
      rows: "18.5K",
      locked: false,
    },
    {
      id: "marketing-campaigns",
      name: "Marketing Campaigns",
      description:
        "Promotional campaigns, offers, discounts, and marketing performance data",
      tagline: "Campaign details and promotional offers",
      tables: [
        "Campaigns",
        "Offers",
        "Discounts",
        "Promotion Schedule",
        "Campaign Performance",
      ],
      size: "280 MB",
      rows: "8.2K",
      locked: false,
    },
    {
      id: "guest-loyalty",
      name: "Guest Loyalty Data",
      description:
        "Customer loyalty program data including points, rewards, membership tiers, and redemptions",
      tagline: "Loyalty program and rewards information",
      tables: [
        "Loyalty Members",
        "Points Balance",
        "Rewards Catalog",
        "Redemptions",
        "Member Tiers",
      ],
      size: "1.8 GB",
      rows: "342K",
      locked: false,
    },
    {
      id: "guest-order-history",
      name: "Guest Order History",
      description:
        "Historical order data including order details, items purchased, payment methods, and order frequency",
      tagline: "Complete guest transaction history",
      tables: [
        "Orders",
        "Order Items",
        "Order Totals",
        "Payment Methods",
        "Order Frequency",
        "Guest Preferences",
      ],
      size: "12.4 GB",
      rows: "2.8M",
      locked: false,
    },
  ],
  branding: {
    primaryColor: "#FF6B35",
    accentColor: "#FFF5F0",
  },
  user: {
    name: "Brandon Barton",
    email: "brandon@getbite.com",
  },
};
