import { TenantConfig } from "./types";

export const solinkConfig: TenantConfig = {
  id: "solink",
  name: "Solink",
  logo: "/brands/icons/solink.png",
  datasets: [
    // Tier 1: Core Video & Operations Data
    {
      id: "video-analytics",
      name: "Video Analytics & Events",
      description:
        "AI-detected events from video feeds including motion detection, object recognition, and behavioral analytics",
      tagline: "AI-powered video intelligence and event detection",
      tables: [
        "Video Events",
        "Camera Metadata",
        "AI Detections",
        "Video Clips",
        "Search Results",
      ],
      size: "1.2 TB",
      rows: "2.4B",
      tier: 1,
      locked: false,
      pricing: "$8 / location / month",
      refreshRate: "Real-time",
    },
    {
      id: "pos-integration",
      name: "POS Transaction Data",
      description:
        "Point-of-sale data synced with video footage for transaction verification, void analysis, and exception reporting",
      tagline: "Video-linked POS transactions and exception alerts",
      tables: [
        "POS Transactions",
        "Transaction Items",
        "Voids & Refunds",
        "Video Correlations",
        "Exception Reports",
      ],
      size: "89.6 GB",
      rows: "456M",
      tier: 1,
      locked: false,
      pricing: "$5 / location / month",
      refreshRate: "Real-time",
    },
    // Tier 2: Operational Intelligence
    {
      id: "occupancy-traffic",
      name: "Occupancy & Traffic Analytics",
      description:
        "Real-time occupancy tracking, traffic counting, dwell-time analysis, and customer flow patterns across locations",
      tagline: "Customer traffic and space utilization insights",
      tables: [
        "Occupancy Logs",
        "Traffic Counts",
        "Dwell Time Analysis",
        "Heat Maps",
        "Flow Patterns",
      ],
      size: "124.8 GB",
      rows: "687M",
      tier: 2,
      locked: true,
      pricing: "+$6 / location / month",
      refreshRate: "Real-time",
    },
    {
      id: "service-quality",
      name: "Service Quality Monitoring",
      description:
        "AI-powered detection of dirty tables, wait times, queue lengths, and service speed metrics for operational optimization",
      tagline: "Automated service quality and cleanliness tracking",
      tables: [
        "Table Status",
        "Wait Time Metrics",
        "Queue Analysis",
        "Service Speed",
        "Cleanliness Alerts",
      ],
      size: "67.3 GB",
      rows: "298M",
      tier: 2,
      locked: true,
      pricing: "+$7 / location / month",
      refreshRate: "Real-time",
    },
    {
      id: "inventory-security",
      name: "Inventory & Security Alerts",
      description:
        "Visual stock level monitoring, security incident detection, alarm verification, and loss prevention analytics",
      tagline: "Video-verified security and inventory tracking",
      tables: [
        "Stock Levels",
        "Security Incidents",
        "Alarm Events",
        "Loss Prevention",
        "Access Logs",
      ],
      size: "52.4 GB",
      rows: "234M",
      tier: 2,
      locked: true,
      pricing: "+$5 / location / month",
      refreshRate: "Real-time",
    },
    {
      id: "speed-of-service",
      name: "Speed of Service Analytics",
      description:
        "Comprehensive service timing metrics including order-to-delivery times, drive-thru speeds, table turnover rates, and employee performance tracking",
      tagline: "End-to-end service timing and efficiency metrics",
      tables: [
        "Order Timing",
        "Drive-Thru Metrics",
        "Table Turnover",
        "Employee Performance",
        "Service Benchmarks",
        "Peak Hour Analysis",
      ],
      size: "94.2 GB",
      rows: "412M",
      tier: 2,
      locked: true,
      pricing: "+$8 / location / month",
      refreshRate: "Real-time",
    },
    {
      id: "competitor-analysis",
      name: "Competitor Benchmarking",
      description:
        "Multi-location performance comparison, industry benchmarks, best practices identification, and competitive positioning analytics",
      tagline: "Cross-location and industry performance insights",
      tables: [
        "Location Rankings",
        "Industry Benchmarks",
        "Best Practices",
        "Performance Comparisons",
        "Market Share Indicators",
      ],
      size: "38.6 GB",
      rows: "156M",
      tier: 2,
      locked: true,
      pricing: "+$10 / location / month",
      refreshRate: "Weekly",
    },
  ],
  branding: {
    primaryColor: "#0066FF",
    accentColor: "#E6F0FF",
  },
  user: {
    name: "Michael Matta",
    email: "mmatta@solink.com",
  },
};
