import { TenantConfig } from "./types";

export const thanxConfig: TenantConfig = {
  id: "thanx",
  name: "Thanx",
  logo: "/brands/icons/thanx.jpeg",
  datasets: [
    // Tier 1: Core Loyalty & Customer Data
    {
      id: "loyalty-members",
      name: "Loyalty Members & Transactions",
      description:
        "Complete loyalty member profiles, point transactions, redemptions, tier status, enrollment sources, and lifetime value analytics",
      tagline: "Full loyalty member database and transaction history",
      tables: [
        "Loyalty Members",
        "Point Transactions",
        "Reward Redemptions",
        "Tier Status",
        "Enrollment Data",
        "Member Lifetime Value",
      ],
      size: "234.8 GB",
      rows: "1.2B",
      tier: 1,
      locked: false,
      pricing: "$5 / location / month",
      refreshRate: "Real-time",
    },
    {
      id: "customer-purchases",
      name: "Customer Purchase History",
      description:
        "Complete transaction history across all channels (in-store, online ordering, mobile app) with item-level detail and payment data",
      tagline: "Multi-channel purchase data with item detail",
      tables: [
        "Transactions",
        "Transaction Items",
        "Order Sources",
        "Payment Methods",
        "Purchase Frequency",
      ],
      size: "456.2 GB",
      rows: "2.8B",
      tier: 1,
      locked: false,
      pricing: "$6 / location / month",
      refreshRate: "Real-time",
    },
    // Tier 2: Marketing & Engagement Intelligence
    {
      id: "marketing-campaigns",
      name: "Marketing Campaigns & Automation",
      description:
        "Campaign performance data, automated journey analytics, email/SMS engagement metrics, and conversion tracking",
      tagline: "Complete marketing campaign and automation analytics",
      tables: [
        "Campaigns",
        "Campaign Performance",
        "Automated Journeys",
        "Email Metrics",
        "SMS Metrics",
        "Conversion Events",
      ],
      size: "124.6 GB",
      rows: "687M",
      tier: 2,
      locked: true,
      pricing: "+$7 / location / month",
      refreshRate: "Real-time",
    },
    {
      id: "customer-segments",
      name: "Customer Segments & Behavior",
      description:
        "Dynamic customer segments, behavioral analytics, visit frequency patterns, lifecycle stages, and churn risk indicators",
      tagline: "Advanced customer segmentation and behavior insights",
      tables: [
        "Customer Segments",
        "Behavioral Analytics",
        "Visit Patterns",
        "Lifecycle Stages",
        "Churn Risk Scores",
        "RFM Analysis",
      ],
      size: "89.4 GB",
      rows: "342M",
      tier: 2,
      locked: true,
      pricing: "+$6 / location / month",
      refreshRate: "Daily",
    },
    {
      id: "offers-rewards",
      name: "Offers & Rewards Performance",
      description:
        "Reward redemption analytics, offer effectiveness, margin impact analysis, discount usage patterns, and non-discount reward performance",
      tagline: "Reward program economics and offer optimization",
      tables: [
        "Offers",
        "Reward Performance",
        "Margin Impact",
        "Discount Analytics",
        "Access Pass Usage",
        "Hidden Menu Performance",
      ],
      size: "67.8 GB",
      rows: "298M",
      tier: 2,
      locked: true,
      pricing: "+$8 / location / month",
      refreshRate: "Hourly",
    },
    {
      id: "digital-ordering",
      name: "Digital Ordering Analytics",
      description:
        "Mobile app usage, online ordering behavior, cart analytics, checkout conversion rates, and repeat ordering patterns",
      tagline: "Digital ordering and app engagement metrics",
      tables: [
        "App Sessions",
        "Order Flows",
        "Cart Analytics",
        "Conversion Funnels",
        "Repeat Orders",
        "App Retention",
      ],
      size: "156.2 GB",
      rows: "724M",
      tier: 2,
      locked: true,
      pricing: "+$5 / location / month",
      refreshRate: "Real-time",
    },
    {
      id: "competitor-benchmarking",
      name: "Competitor Benchmarking",
      description:
        "Multi-location performance comparison, industry benchmarks, loyalty program effectiveness rankings, engagement metrics, and competitive positioning analytics",
      tagline: "Cross-location and industry performance insights",
      tables: [
        "Location Rankings",
        "Industry Benchmarks",
        "Loyalty Program Comparisons",
        "Engagement Benchmarks",
        "Best Practices",
        "Market Position",
      ],
      size: "38.4 GB",
      rows: "164M",
      tier: 2,
      locked: true,
      pricing: "+$9 / location / month",
      refreshRate: "Weekly",
    },
  ],
  branding: {
    primaryColor: "#FF6B35",
    accentColor: "#FFF5F0",
  },
  user: {
    name: "Zach Goldstein",
    email: "zach@thanx.com",
  },
};

