import { TenantConfig } from "./types";

export const toastConfig: TenantConfig = {
  id: "toast",
  name: "Toast",
  logo: "/brands/icons/toast.svg",
  datasets: [
    // Tier 1: Core Transaction Data
    {
      id: "orders-transactions",
      name: "Orders & Transactions",
      description:
        "Complete order history including items, modifiers, pricing, payment methods, and timestamps",
      tagline: "Full transaction history with line-item detail",
      tables: [
        "Orders",
        "Order Items",
        "Order Modifiers",
        "Payments",
        "Refunds",
        "Voids",
      ],
      size: "45.2 GB",
      rows: "287M",
      tier: 1,
      locked: false,
      pricing: "$5 / location / month",
      refreshRate: "Real-time",
    },
    {
      id: "menu-catalog",
      name: "Menu Catalog",
      description:
        "Menu structure, items, pricing, availability schedules, and modifier groups",
      tagline: "Complete menu hierarchy and configuration",
      tables: [
        "Menus",
        "Menu Groups",
        "Menu Items",
        "Item Modifiers",
        "Pricing Rules",
        "Availability Windows",
      ],
      size: "2.8 GB",
      rows: "12.4M",
      tier: 1,
      locked: false,
      pricing: "$2 / location / month",
      refreshRate: "Hourly",
    },
    {
      id: "guest-data",
      name: "Guest Profiles",
      description:
        "Customer profiles with contact info, order history, preferences, and loyalty points",
      tagline: "Customer data with order history and preferences",
      tables: [
        "Guests",
        "Guest Orders",
        "Guest Preferences",
        "Loyalty Points",
        "Marketing Preferences",
      ],
      size: "8.6 GB",
      rows: "45.3M",
      tier: 1,
      locked: false,
      pricing: "$3 / location / month",
      refreshRate: "Daily",
    },
    // Tier 2: Operational Analytics
    {
      id: "labor-management",
      name: "Labor & Shifts",
      description:
        "Employee schedules, clock-in/out times, break tracking, labor costs, and productivity metrics",
      tagline: "Complete labor tracking and cost analysis",
      tables: [
        "Employees",
        "Shifts",
        "Time Punches",
        "Break Logs",
        "Labor Costs",
        "Job Codes",
      ],
      size: "12.3 GB",
      rows: "89.7M",
      tier: 2,
      locked: true,
      pricing: "+$4 / location / month",
      refreshRate: "Hourly",
    },
    {
      id: "inventory-data",
      name: "Inventory Management",
      description:
        "Stock levels, consumption rates, waste tracking, transfers, and supplier information",
      tagline: "Real-time inventory with waste and cost tracking",
      tables: [
        "Inventory Items",
        "Stock Levels",
        "Consumption Logs",
        "Waste Tracking",
        "Transfers",
        "Suppliers",
        "Purchase Orders",
      ],
      size: "6.4 GB",
      rows: "34.8M",
      tier: 2,
      locked: true,
      pricing: "+$3 / location / month",
      refreshRate: "Daily",
    },
    {
      id: "kitchen-operations",
      name: "Kitchen Operations",
      description:
        "Order routing, prep times, ticket fulfillment, kitchen display system data, and expedite metrics",
      tagline: "Kitchen efficiency and order fulfillment tracking",
      tables: [
        "Kitchen Tickets",
        "Prep Times",
        "Order Routing",
        "Fulfillment Times",
        "Station Performance",
      ],
      size: "18.9 GB",
      rows: "156.2M",
      tier: 2,
      locked: true,
      pricing: "+$3.5 / location / month",
      refreshRate: "Real-time",
    },
    // Tier 3: Advanced Analytics & Insights
    {
      id: "sales-analytics",
      name: "Sales Analytics",
      description:
        "Aggregated sales performance by item, category, daypart, server, and location with trends",
      tagline: "Pre-aggregated sales insights and trends",
      tables: [
        "Sales Summary",
        "Item Performance",
        "Daypart Analysis",
        "Server Performance",
        "Category Trends",
        "Mix Analysis",
      ],
      size: "4.2 GB",
      rows: "18.6M",
      tier: 3,
      locked: true,
      pricing: "+$6 / location / month",
      refreshRate: "Daily",
    },
    {
      id: "financial-reporting",
      name: "Financial Reporting",
      description:
        "Revenue summaries, payment reconciliation, tips distribution, cash management, and tax reporting",
      tagline: "Financial reconciliation and reporting data",
      tables: [
        "Revenue Summary",
        "Payment Reconciliation",
        "Tips Distribution",
        "Cash Management",
        "Tax Calculations",
        "Deposit Records",
      ],
      size: "3.8 GB",
      rows: "15.4M",
      tier: 3,
      locked: true,
      pricing: "+$5 / location / month",
      refreshRate: "Daily",
    },
    {
      id: "competitor-benchmarks",
      name: "Competitor Benchmarking",
      description:
        "Performance comparison against industry competitors with rankings, trends, and best practice insights",
      tagline: "Competitive performance benchmarking",
      tables: [
        "Competitor Rankings",
        "Performance Metrics",
        "Comparative Trends",
        "Best Practices",
        "Anomaly Detection",
      ],
      size: "1.9 GB",
      rows: "8.2M",
      tier: 3,
      locked: true,
      pricing: "+$8 / location / month",
      refreshRate: "Weekly",
    },
  ],
  branding: {
    primaryColor: "#FF4C00",
    accentColor: "#FFF5F0",
  },
  user: {
    name: "Aman Narang",
    email: "aman@toasttab.com",
  },
};
